name: Deploy API to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - "packages/api/**"
      - "packages/shared/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.5.1"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.6.1

      - name: Install dependencies
        run: pnpm i

      - name: Build shared package
        run: |
          cd packages/shared
          pnpm build

      - name: Generate and run migrations
        run: |
          cd packages/api
          pnpm db:generate
          pnpm db:migrate
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
          NODE_OPTIONS: "--dns-result-order=ipv4first"

      - name: Verify wrangler configuration
        run: |
          cd packages/api
          if [ -f "wrangler.json" ]; then
            echo "wrangler.json exists"
          elif [ -f "wrangler.jsonc" ]; then
            echo "wrangler.jsonc exists, renaming to wrangler.json"
            mv wrangler.jsonc wrangler.json
          else
            echo "No wrangler configuration found"
            exit 1
          fi

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "packages/api"
          command: deploy --minify
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
